### ISSUE TITLE
broccoli-esnext will be deprecated.

### ISSUE THREAD

**Issue by shinnn** [rwjblue/ember-cli-esnext#16]
Hi, I'm an author of [broccoli-esnext](https://www.npmjs.com/package/broccoli-esnext).

I will inform you of deprecation of broccoli-esnext. It finished its roles because [the upstream project is deprecated](https://github.com/esnext/esnext/commit/5213f237c71bf7c5d1186d810c1c48f66b62a747) and now we can use [babel plugin](https://github.com/babel/broccoli-babel-transpiler) instead.

Thanks for using my plugin as a dependency of this project!

**Comment by rwjblue** [comment]
@shinnn - Thank you very much for taking the time to open an issue for this! It is great to see that some package maintainers care enough about their users to notify them when the package is being deprecated.

As for ember-cli-esnext, it has already been replaced as the default ES6/ES2015 transpiler in Ember CLI.  I will update the readme to reflect that it is deprecated...

**Comment by shinnn** [comment]
I should update the readme and [deprecate the npm package](https://docs.npmjs.com/cli/deprecate), too.

**Comment by shinnn** [comment]
Just deprecated broccoli-esnext.

```
$ npm install broccoli-esnext
npm WARN deprecated broccoli-esnext@0.5.1: Use broccoli-babel-transpiler instead.
broccoli-esnext@0.5.1 node_modules/broccoli-esnext
├── chalk@1.0.0 (ansi-styles@2.0.1, escape-string-regexp@1.0.3, supports-color@1.3.1, strip-ansi@2.0.1, has-ansi@1.0.3)
└── broccoli-filter@0.1.12 (broccoli-writer@0.1.1, promise-map-series@0.2.1, walk-sync@0.1.3, mkdirp@0.3.5, rsvp@3.0.18, quick-temp@0.1.2, broccoli-kitchen-sink-helpers@0.2.6)

```

**Comment by shinnn** [comment]
Fixed in https://github.com/rwjblue/ember-cli-esnext/commit/72ca6222c9357c13602ac5613d24b600fc2fb4e3.
