### ISSUE TITLE
Add support for ES6 classes to extend Ember classes (e.g. Ember.Object)

### ISSUE THREAD

**Issue by jayphelps** [rwjblue/ember-cli-esnext#7]
```javascript
class Person extends Ember.Object {
  init() {
    // do work, son.
  }
}
```
This is easier to do with traceur since they abstract class creation to a runtime function `$traceurRuntime.createClass`. I'm not sure how we would do it with esnext. Seems like we'd have to override the output itself some how.

I have no idea how we'd support observers, computed properties, etc...This is prolly a "big picture" issue with Ember long term.

For example, this is *not* valid ES6:

```javascript
var foo =  {
  init() {
  
  }.property()
  /// Unexpected token .
};
```

@Annotations maybe?

**Comment by jehrhardt** [comment]
What is about using sweet.js macros to translate es6 class syntax to es5 Ember code?

**Comment by knownasilya** [comment]
@jehrhardt that's not a bad idea, could be a nice ember-cli preprocessor addon.

**Comment by listepo** [comment]
+1

**Comment by stefanpenner** [comment]
this library is deprecated in-favor of ember-cli-babel. As esnext + babel essentially merged forces.

**Comment by perlun** [comment]
For reference, [here](https://github.com/babel/ember-cli-babel) is ember-cli-babel.
